version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  backend:
    build: .
    env_file: .env
    depends_on:
      - db
      - qdrant
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
volumes:
  db-data:
