[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F"]
ignore = []

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
